[project]
name = "mcpSuunto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Louison Masson", email = "louison.masson@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
mcpSuunto = "mcpSuunto:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
